//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SociedadElHuerfanitoEntities : DbContext
    {
        public SociedadElHuerfanitoEntities()
            : base("name=SociedadElHuerfanitoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adopcion> Adopcion { get; set; }
        public virtual DbSet<Adoptante> Adoptante { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoMascota> TipoMascota { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<vw_MascotasDisponibles> vw_MascotasDisponibles { get; set; }
    }
}
