//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MascotasDisponibles
    {
        public int id_mascota { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public string raza { get; set; }
        public Nullable<int> edad_meses { get; set; }
        public string sexo { get; set; }
        public string estado { get; set; }
    }
}
